spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devel-cadastro-db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
